version: "3.8"

services:
  users_service:
    container_name: users_service
    build: ./users-service
    env_file:
      - .env
    command:
      [
        "sh",
        "-c",
        "pip install debugpy && python -m debugpy --listen 0.0.0.0:5678 -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000",
      ]
    volumes:
      - ./users-service/:/app
    ports:
      - 8000:8000
      - 5678:5678
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:14.3-alpine
    container_name: postgres_container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports: 
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:6.10
    depends_on:
      - postgres_db
    env_file:
      - .env
    ports:
      - "5050:5050"

volumes:
  postgres_data:
  